version: 2
jobs:
  build:
    #machine: true
    docker:
      # specify the version you desire here
      - image: circleci/node:10

    working_directory: ~/garbarino-com/checkout-alarms

    environment:
      ARTIFACT_NAME: checkout-alarms

    steps:
      - checkout
      - run:
          name: Get ENVIRONMENT_NAME
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
            echo 'export ENVIRONMENT_NAME=staging' >> $BASH_ENV
            else
            echo 'export ENVIRONMENT_NAME=ci' >> $BASH_ENV
            fi
      - run:
          name: Set Version
          command: |
            echo $CIRCLE_SHA1-$CIRCLE_BUILD_NUM > /tmp/version
      - run:
          name: Install aws dependencies
          command: |
            sudo apt-get update
            sudo apt-get install awscli
      - run:
          name: Install typescript dependencies
          command: npm install typescript -g
      - run:
          name: Deploy client
          command: |
            cd client
            chmod +x deploy.sh
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              ./deploy.sh checkout-alarms-staging.garbarino.com E2TQ3NHJMCOJXP
            else
              echo "Another Branch"
            fi
      - run:
          name: Start Deploy Server
          command: cd ~/garbarino-com/checkout-alarms
      - run: rm -rf node_modules
      - run: yarn --ignore-engines
      - run: tsc
      - run: mkdir -pv /tmp/release
      - run: cp -r `ls | grep -v "^statics" | grep -v "^node_modules" | grep -v "^client"` /tmp/release
      - run: aws s3 cp s3://garbarino-deploy-scripts/deploy_ecs.sh /tmp/release/deploy_ecs.sh
      - run: chmod +x /tmp/release/deploy_ecs.sh
      - run:
          name: Deploy Server
          command: /tmp/release/deploy_ecs.sh $ENVIRONMENT_NAME $ARTIFACT_NAME