defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8

whitelist: &whitelist
  paths:
    - client/*
    - config/*
    - .npmignore
    - coverage/*
    - dist/*
    - node_modules/*
    - src/*
    - Dockerfile
    - package.json
    - README.md
    - tsconfig.json

version: 2
jobs:
  checkout:
    <<: *defaults

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Install Client Dependencies
          command: cd client && yarn install

          - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          <<: *whitelist 

  build_client:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Build TypeScript code
          command: cd client && yarn build

      - persist_to_workspace:
          root: ~/repo
          <<: *whitelist

  deploy_client:
    <<: *defaults

    steps:
      - run:
          name: Install aws dependencies
          command: |
            sudo apt-get update
            sudo apt-get install awscli
      - run:
          name: Deploy client
          command: |
            cd client
            chmod +x deploy.sh
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              ./deploy.sh checkout-alarms-staging.garbarino.com E2TQ3NHJMCOJXP
            else
              echo "Another Branch"
            fi
workflows:
  version: 2

  build:
    jobs:
      - checkout
      - build_client:
          requires:
            - checkout
  release:
    jobs:
      - checkout:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - build_client:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
          requires:
            - checkout
      - deploy_client:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
          requires:
            - build_client