export let schema = {
  title: "Alarm",
  type: "object",
  required: ["brand"],
  properties: {
    _id: { type: "string", title: "id" },
    brand: { type: "string", title: "brand", default: "" },
    platform: { type: "string", title: "platform", default: "" },
    promo: { type: "string", title: "promo", default: "" },
    source: { type: "string", title: "source", default: "" },
    chatID: { type: "string", title: "chat Id", default: "" },
    calendar: {
      type: "object",
      title: "calendar",
      properties: {
        dom: {
          type: "object",
          title: "domingo",
          properties: {
            A1: { type: "number", title: "0a1" },
            A2: { type: "number", title: "1a2" },
            A3: { type: "number", title: "2a3" },
            A4: { type: "number", title: "3a4" },
            A5: { type: "number", title: "4a5" },
            A6: { type: "number", title: "5a6" },
            A7: { type: "number", title: "6a7" },
            A8: { type: "number", title: "7a8" },
            A9: { type: "number", title: "8a9" },
            A10: { type: "number", title: "9a10" },
            A11: { type: "number", title: "10a11" },
            A12: { type: "number", title: "11a12" },
            A13: { type: "number", title: "12a13" },
            A14: { type: "number", title: "13a14" },
            A15: { type: "number", title: "14a15" },
            A16: { type: "number", title: "15a16" },
            A17: { type: "number", title: "16a17" },
            A18: { type: "number", title: "17a18" },
            A19: { type: "number", title: "18a19" },
            A20: { type: "number", title: "19a20" },
            A21: { type: "number", title: "20a21" },
            A22: { type: "number", title: "21a22" },
            A23: { type: "number", title: "22a23" },
            A24: { type: "number", title: "23a24" }
          }
        },
        lun: {
          type: "object",
          title: "lunes",
          properties: {
            A1: { type: "number", title: "0a1" },
            A2: { type: "number", title: "1a2" },
            A3: { type: "number", title: "2a3" },
            A4: { type: "number", title: "3a4" },
            A5: { type: "number", title: "4a5" },
            A6: { type: "number", title: "5a6" },
            A7: { type: "number", title: "6a7" },
            A8: { type: "number", title: "7a8" },
            A9: { type: "number", title: "8a9" },
            A10: { type: "number", title: "9a10" },
            A11: { type: "number", title: "10a11" },
            A12: { type: "number", title: "11a12" },
            A13: { type: "number", title: "12a13" },
            A14: { type: "number", title: "13a14" },
            A15: { type: "number", title: "14a15" },
            A16: { type: "number", title: "15a16" },
            A17: { type: "number", title: "16a17" },
            A18: { type: "number", title: "17a18" },
            A19: { type: "number", title: "18a19" },
            A20: { type: "number", title: "19a20" },
            A21: { type: "number", title: "20a21" },
            A22: { type: "number", title: "21a22" },
            A23: { type: "number", title: "22a23" },
            A24: { type: "number", title: "23a24" }
          }
        },
        mar: {
          type: "object",
          title: "martes",
          properties: {
            A1: { type: "number", title: "0a1" },
            A2: { type: "number", title: "1a2" },
            A3: { type: "number", title: "2a3" },
            A4: { type: "number", title: "3a4" },
            A5: { type: "number", title: "4a5" },
            A6: { type: "number", title: "5a6" },
            A7: { type: "number", title: "6a7" },
            A8: { type: "number", title: "7a8" },
            A9: { type: "number", title: "8a9" },
            A10: { type: "number", title: "9a10" },
            A11: { type: "number", title: "10a11" },
            A12: { type: "number", title: "11a12" },
            A13: { type: "number", title: "12a13" },
            A14: { type: "number", title: "13a14" },
            A15: { type: "number", title: "14a15" },
            A16: { type: "number", title: "15a16" },
            A17: { type: "number", title: "16a17" },
            A18: { type: "number", title: "17a18" },
            A19: { type: "number", title: "18a19" },
            A20: { type: "number", title: "19a20" },
            A21: { type: "number", title: "20a21" },
            A22: { type: "number", title: "21a22" },
            A23: { type: "number", title: "22a23" },
            A24: { type: "number", title: "23a24" }
          }
        },
        mie: {
          type: "object",
          title: "miercoles",
          properties: {
            A1: { type: "number", title: "0a1" },
            A2: { type: "number", title: "1a2" },
            A3: { type: "number", title: "2a3" },
            A4: { type: "number", title: "3a4" },
            A5: { type: "number", title: "4a5" },
            A6: { type: "number", title: "5a6" },
            A7: { type: "number", title: "6a7" },
            A8: { type: "number", title: "7a8" },
            A9: { type: "number", title: "8a9" },
            A10: { type: "number", title: "9a10" },
            A11: { type: "number", title: "10a11" },
            A12: { type: "number", title: "11a12" },
            A13: { type: "number", title: "12a13" },
            A14: { type: "number", title: "13a14" },
            A15: { type: "number", title: "14a15" },
            A16: { type: "number", title: "15a16" },
            A17: { type: "number", title: "16a17" },
            A18: { type: "number", title: "17a18" },
            A19: { type: "number", title: "18a19" },
            A20: { type: "number", title: "19a20" },
            A21: { type: "number", title: "20a21" },
            A22: { type: "number", title: "21a22" },
            A23: { type: "number", title: "22a23" },
            A24: { type: "number", title: "23a24" }
          }
        },
        jue: {
          type: "object",
          title: "jueves",
          properties: {
            A1: { type: "number", title: "0a1" },
            A2: { type: "number", title: "1a2" },
            A3: { type: "number", title: "2a3" },
            A4: { type: "number", title: "3a4" },
            A5: { type: "number", title: "4a5" },
            A6: { type: "number", title: "5a6" },
            A7: { type: "number", title: "6a7" },
            A8: { type: "number", title: "7a8" },
            A9: { type: "number", title: "8a9" },
            A10: { type: "number", title: "9a10" },
            A11: { type: "number", title: "10a11" },
            A12: { type: "number", title: "11a12" },
            A13: { type: "number", title: "12a13" },
            A14: { type: "number", title: "13a14" },
            A15: { type: "number", title: "14a15" },
            A16: { type: "number", title: "15a16" },
            A17: { type: "number", title: "16a17" },
            A18: { type: "number", title: "17a18" },
            A19: { type: "number", title: "18a19" },
            A20: { type: "number", title: "19a20" },
            A21: { type: "number", title: "20a21" },
            A22: { type: "number", title: "21a22" },
            A23: { type: "number", title: "22a23" },
            A24: { type: "number", title: "23a24" }
          }
        },
        vie: {
          type: "object",
          title: "viernes",
          properties: {
            A1: { type: "number", title: "0a1" },
            A2: { type: "number", title: "1a2" },
            A3: { type: "number", title: "2a3" },
            A4: { type: "number", title: "3a4" },
            A5: { type: "number", title: "4a5" },
            A6: { type: "number", title: "5a6" },
            A7: { type: "number", title: "6a7" },
            A8: { type: "number", title: "7a8" },
            A9: { type: "number", title: "8a9" },
            A10: { type: "number", title: "9a10" },
            A11: { type: "number", title: "10a11" },
            A12: { type: "number", title: "11a12" },
            A13: { type: "number", title: "12a13" },
            A14: { type: "number", title: "13a14" },
            A15: { type: "number", title: "14a15" },
            A16: { type: "number", title: "15a16" },
            A17: { type: "number", title: "16a17" },
            A18: { type: "number", title: "17a18" },
            A19: { type: "number", title: "18a19" },
            A20: { type: "number", title: "19a20" },
            A21: { type: "number", title: "20a21" },
            A22: { type: "number", title: "21a22" },
            A23: { type: "number", title: "22a23" },
            A24: { type: "number", title: "23a24" }
          }
        },
        sab: {
          type: "object",
          title: "sabado",
          properties: {
            A1: { type: "number", title: "0a1" },
            A2: { type: "number", title: "1a2" },
            A3: { type: "number", title: "2a3" },
            A4: { type: "number", title: "3a4" },
            A5: { type: "number", title: "4a5" },
            A6: { type: "number", title: "5a6" },
            A7: { type: "number", title: "6a7" },
            A8: { type: "number", title: "7a8" },
            A9: { type: "number", title: "8a9" },
            A10: { type: "number", title: "9a10" },
            A11: { type: "number", title: "10a11" },
            A12: { type: "number", title: "11a12" },
            A13: { type: "number", title: "12a13" },
            A14: { type: "number", title: "13a14" },
            A15: { type: "number", title: "14a15" },
            A16: { type: "number", title: "15a16" },
            A17: { type: "number", title: "16a17" },
            A18: { type: "number", title: "17a18" },
            A19: { type: "number", title: "18a19" },
            A20: { type: "number", title: "19a20" },
            A21: { type: "number", title: "20a21" },
            A22: { type: "number", title: "21a22" },
            A23: { type: "number", title: "22a23" },
            A24: { type: "number", title: "23a24" }
          }
        }
      }
    }
  }
};

export let prefilled = {
  calendar: {
    dom: {
      A1: 5,
      A2: 5,
      A3: 5,
      A4: 5,
      A5: 5,
      A6: 5,
      A7: 5,
      A8: 5,
      A9: 5,
      A10: 5,
      A11: 5,
      A12: 5,
      A13: 5,
      A14: 5,
      A15: 5,
      A16: 5,
      A17: 5,
      A18: 5,
      A19: 5,
      A20: 5,
      A21: 5,
      A22: 5,
      A23: 5,
      A24: 5
    },
    lun: {
      A1: 5,
      A2: 5,
      A3: 5,
      A4: 5,
      A5: 5,
      A6: 5,
      A7: 5,
      A8: 5,
      A9: 5,
      A10: 5,
      A11: 5,
      A12: 5,
      A13: 5,
      A14: 5,
      A15: 5,
      A16: 5,
      A17: 5,
      A18: 5,
      A19: 5,
      A20: 5,
      A21: 5,
      A22: 5,
      A23: 5,
      A24: 5
    },
    mar: {
      A1: 5,
      A2: 5,
      A3: 5,
      A4: 5,
      A5: 5,
      A6: 5,
      A7: 5,
      A8: 5,
      A9: 5,
      A10: 5,
      A11: 5,
      A12: 5,
      A13: 5,
      A14: 5,
      A15: 5,
      A16: 5,
      A17: 5,
      A18: 5,
      A19: 5,
      A20: 5,
      A21: 5,
      A22: 5,
      A23: 5,
      A24: 5
    },
    mie: {
      A1: 5,
      A2: 5,
      A3: 5,
      A4: 5,
      A5: 5,
      A6: 5,
      A7: 5,
      A8: 5,
      A9: 5,
      A10: 5,
      A11: 5,
      A12: 5,
      A13: 5,
      A14: 5,
      A15: 5,
      A16: 5,
      A17: 5,
      A18: 5,
      A19: 5,
      A20: 5,
      A21: 5,
      A22: 5,
      A23: 5,
      A24: 5
    },
    jue: {
      A1: 5,
      A2: 5,
      A3: 5,
      A4: 5,
      A5: 5,
      A6: 5,
      A7: 5,
      A8: 5,
      A9: 5,
      A10: 5,
      A11: 5,
      A12: 5,
      A13: 5,
      A14: 5,
      A15: 5,
      A16: 5,
      A17: 5,
      A18: 5,
      A19: 5,
      A20: 5,
      A21: 5,
      A22: 5,
      A23: 5,
      A24: 5
    },
    vie: {
      A1: 5,
      A2: 5,
      A3: 5,
      A4: 5,
      A5: 5,
      A6: 5,
      A7: 5,
      A8: 5,
      A9: 5,
      A10: 5,
      A11: 5,
      A12: 5,
      A13: 5,
      A14: 5,
      A15: 5,
      A16: 5,
      A17: 5,
      A18: 5,
      A19: 5,
      A20: 5,
      A21: 5,
      A22: 5,
      A23: 5,
      A24: 5
    },
    sab: {
      A1: 5,
      A2: 5,
      A3: 5,
      A4: 5,
      A5: 5,
      A6: 5,
      A7: 5,
      A8: 5,
      A9: 5,
      A10: 5,
      A11: 5,
      A12: 5,
      A13: 5,
      A14: 5,
      A15: 5,
      A16: 5,
      A17: 5,
      A18: 5,
      A19: 5,
      A20: 5,
      A21: 5,
      A22: 5,
      A23: 5,
      A24: 5
    }
  },
  platform: "",
  brand: "",
  promo: "",
  source: "",
  chatID: "@ci_monitor_sale"
};
